// views/svelte-front/src/components/Canvas.svelte
<script>
    import { onMount, onDestroy, createEventDispatcher } from "svelte";
    import painteer from "painteer/js/core";

    let refCanvas;
    let refContextualMenu;
    let canvasFns;

    

    const addTextOpenDialogDispatcher = createEventDispatcher();
    const addImageOpenDialogDispatcher = createEventDispatcher();
    const onCanvasReadyDispatcher = createEventDispatcher();

    onMount(() => {
        if (refCanvas) {
            canvasFns = painteer.setCanvas(
                refCanvas,
                closeContextualMenu,
                refContextualMenu
            );

            document.addEventListener("mousedown", canvasFns.mouseDown, false);
            document.addEventListener("mouseup", canvasFns.mouseUp, false);
            document.addEventListener("mousemove", canvasFns.mouseMove, false);

            onCanvasReadyDispatcher("onCanvasReadyListener", {
                canvasFns,
                canvas: refCanvas,
            });
        }
    });

    onDestroy(() => {
        canvasFns.removeContextMenuListerner();
        document.removeEventListener("mousedown", canvasFns.mouseDown, false);
        document.removeEventListener("mouseup", canvasFns.mouseUp, false);
        document.removeEventListener("mousemove", canvasFns.mouseMove, false);
    });

    function closeContextualMenu() {
        refContextualMenu.classList.add("hide");
    }

    function onAddText(event) {
        const position = painteer.getMousePosition(refCanvas, event);
        addTextOpenDialogDispatcher('onAddTextOpenDialogListener', position);
        closeContextualMenu();
    }

    function onAddImg(event) {
        const position = painteer.getMousePosition(refCanvas, event);
        addImageOpenDialogDispatcher('onAddImageOpenDialogListener', position);
        closeContextualMenu();
    }
</script>

<main aria-label="Painting area">
    <canvas bind:this={refCanvas} id="canvas" />
    <!-- contextual menu -->
    <div
        bind:this={refContextualMenu}
        id="contextual-menu"
        class="hide"
        aria-hidden="true"
    >
        <ul>
            <li id="add-text" on:click={onAddText}>
                <i class="fa fa-font" />Text
            </li>
            <li id="add-img" on:click={onAddImg}>
                <i class="far fa-image" />Image
            </li>
        </ul>
    </div>
</main>

// views/angular-front/src/app/components/canvas/canvas.component.ts
import { AfterViewInit, Component, ElementRef, EventEmitter, OnDestroy, Output, ViewChild } from "@angular/core";
import painteer from "painteer/js/core";

@Component({
    selector: "app-canvas",
    templateUrl: "./canvas.component.html"
})
export class CanvasComponent implements AfterViewInit, OnDestroy {
    
    canvasFns;
    @ViewChild('refContextualMenu') refContextualMenu: ElementRef;
    @ViewChild('refCanvas') refCanvas: ElementRef;

    @Output("onCanvasReadyListener") onCanvasReadyDispatcher = new EventEmitter();
    @Output("onAddTextOpenDialogListener") addTextOpenDialogDispatcher = new EventEmitter();
    @Output("onAddImageOpenDialogListener") addImageOpenDialogDispatcher = new EventEmitter();


    ngAfterViewInit(): void {
        if (this.refCanvas) {
            this.canvasFns = painteer.setCanvas(
                this.refCanvas.nativeElement,
                this.closeContextualMenu.bind(this),
                this.refContextualMenu.nativeElement
            );

            document.addEventListener("mousedown", this.canvasFns.mouseDown, false);
            document.addEventListener("mouseup", this.canvasFns.mouseUp, false);
            document.addEventListener("mousemove", this.canvasFns.mouseMove, false);

            this.onCanvasReadyDispatcher.emit({
                canvasFns: this.canvasFns,
                canvas: this.refCanvas.nativeElement,
            });
        }
    }

    ngOnDestroy(): void {
        this.canvasFns.removeContextMenuListerner();
        document.removeEventListener("mousedown", this.canvasFns.mouseDown, false);
        document.removeEventListener("mouseup", this.canvasFns.mouseUp, false);
        document.removeEventListener("mousemove", this.canvasFns.mouseMove, false);
    }
    

    closeContextualMenu() {
        this.refContextualMenu.nativeElement.classList.add("hide");
    }

    onAddText(event) {
        const position = painteer.getMousePosition(this.refCanvas.nativeElement, event);
        this.addTextOpenDialogDispatcher.emit(position);
        this.closeContextualMenu();
    }

    onAddImg(event) {
        const position = painteer.getMousePosition(this.refCanvas.nativeElement, event);
        this.addImageOpenDialogDispatcher.emit(position);
        this.closeContextualMenu();
    }


}
<main aria-label="Painting area">
    <canvas #refCanvas id="canvas"></canvas>
    <!-- contextual menu -->
    <div
        #refContextualMenu
        id="contextual-menu"
        class="hide"
        aria-hidden="true"
    >
        <ul>
            <li id="add-text" (click)=onAddText($event)>
                <i class="fa fa-font"></i>Text
            </li>
            <li id="add-img" (click)=onAddImg($event)>
                <i class="far fa-image"></i>Image
            </li>
        </ul>
    </div>
</main>
