// views/vuejs-front/src/components/Canvas.vue
<template>
  <main aria-label="Painting area">
    <canvas ref="refCanvas" id="canvas"></canvas>
    <!-- contextual menu --> 
    <div ref="refContextualMenu" id="contextual-menu" class='hide' aria-hidden="true">
        <ul>
            <li id="add-text" @click="onAddText">
                <i class="fa fa-font"></i>Text
            </li>
            <li id="add-img"
                @click="onAddImg">
                <i class="far fa-image"></i>Image
            </li>
        </ul>
    </div>
  </main>
</template>
<script>

import painteer from "painteer/js/core";

export default {
    props: {
        onAddTextOpenDialogListener: Function,
        onAddImageOpenDialogListener: Function,
        onCanvasReadyListener: Function
    },
    data() {
        return {
            canvasFns: null
        };
    },
    mounted() {
        if (this.$refs.refCanvas) {
            this.canvasFns = painteer.setCanvas(this.$refs.refCanvas, this.closeContextualMenu, this.$refs.refContextualMenu);

            document.addEventListener("mousedown",  this.canvasFns.mouseDown,   false);
            document.addEventListener("mouseup",    this.canvasFns.mouseUp,     false);
            document.addEventListener("mousemove",  this.canvasFns.mouseMove,   false);

            this.onCanvasReadyListener({
                canvasFns: this.canvasFns,
                canvas: this.refCanvas
            });
            
        }
    },
    beforeDestroy() {
        this.canvasFns.removeContextMenuListerner();
        document.removeEventListener("mousedown",   this.canvasFns.mouseDown,   false);
        document.removeEventListener("mouseup",     this.canvasFns.mouseUp,     false);
        document.removeEventListener("mousemove",   this.canvasFns.mouseMove,   false);
    },
    methods: {
        closeContextualMenu() {
            this.$refs.refContextualMenu.classList.add("hide")
        },
        onAddText(event) {
            const position = painteer.getMousePosition(this.$refs.refCanvas, event);
            this.onAddTextOpenDialogListener(position);
            this.closeContextualMenu();
        },
        onAddImg(event) {
            const position = painteer.getMousePosition(this.$refs.refCanvas, event);
            this.onAddImageOpenDialogListener(position);
            this.closeContextualMenu();
        }
    }
}
</script>

// views/react-front/src/components/canvas-component.js
import React from "react";
import painteer from "painteer/js/core";

function Canvas({onCanvasReadyListener, ...props}) {
    const refCanvas = React.useRef();
    const refContextualMenu = React.useRef();

    React.useEffect(() => {
        let canvasFns = null;

        if (refCanvas.current) {
            canvasFns = painteer.setCanvas(refCanvas.current, closeContextualMenu, refContextualMenu.current);

            document.addEventListener("mousedown", canvasFns.mouseDown, false);
            document.addEventListener("mouseup", canvasFns.mouseUp, false);
            document.addEventListener("mousemove", canvasFns.mouseMove, false);

            onCanvasReadyListener({
                canvasFns, canvas: refCanvas.current
            });
            
        }

        return () => {
            canvasFns.removeContextMenuListerner();
            document.removeEventListener("mousedown", canvasFns.mouseDown, false);
            document.removeEventListener("mouseup", canvasFns.mouseUp, false);
            document.removeEventListener("mousemove", canvasFns.mouseMove, false);

            canvasFns = null;
        }

    }, [refCanvas, refContextualMenu, onCanvasReadyListener]);

    function closeContextualMenu() {
        refContextualMenu.current.classList.add("hide");
    }

    return (
        <>
            <main aria-label="Painting area">
                <canvas ref={refCanvas} id="canvas"></canvas>
            </main>
            {/* <!-- contextual menu --> */}
            <div ref={refContextualMenu} id="contextual-menu" className='hide' aria-hidden={true}>
                <ul>
                    <li id="add-text" onClick={(event)=> {
                        const position = painteer.getMousePosition(refCanvas.current, event);
                        props.onAddTextOpenDialogListener(position);
                        closeContextualMenu();
                    }}>
                        <i className="fa fa-font"></i>Text
                    </li>
                    <li id="add-img"
                     onClick={(event)=> {
                        const position = painteer.getMousePosition(refCanvas.current, event);
                        props.onAddImageOpenDialogListener(position);
                        closeContextualMenu();
                    }}>
                        <i className="far fa-image"></i>Image
                    </li>
                </ul>
            </div>
        </>
    );
}

export default Canvas;
