// views/angular-front/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  
  showAddTextDialog;
  showAddImageDialog;
  clickPosition;
  canvasFns;

	onBgChange() {
		this.canvasFns.canvasFns.setCanvasBgColors();
	}

	onAddTextOpenDialogListener(clickPosition) {
    console.log(clickPosition);
		this.showAddTextDialog = true;
		this.clickPosition = clickPosition;
	}

	onAddImageOpenDialogListener(clickPosition) {
		this.showAddImageDialog = true;
		this.clickPosition = clickPosition;
	}

	setCanvasFns(canvaFns) {
		setTimeout(()=>this.canvasFns = canvaFns, 0);
	}

}

<app-header (onBgChange)="onBgChange"></app-header>
<app-canvas
    (onAddImageOpenDialogListener)="onAddImageOpenDialogListener($event)"
    (onAddTextOpenDialogListener)="onAddTextOpenDialogListener($event)"
    (onCanvasReadyListener)="setCanvasFns($event)"></app-canvas>
<app-text-dialog
    [canvasFns]="canvasFns"
	[show]="showAddTextDialog"
	[clickPosition]="clickPosition"
	(onDialogCloseListener)="showAddTextDialog = false"></app-text-dialog>
<app-image-dialog
    [canvasFns]="canvasFns"
	[show]="showAddImageDialog"
	[clickPosition]="clickPosition"
	(onDialogCloseListener)="showAddImageDialog = false"></app-image-dialog>

// views/react-front/src/App.js
import React from "react";

import Header from "./components/header-component";
import Canvas from "./components/canvas-component";
import AddTextDialog from "./components/add-text-dialog-component";
import AddImageDialog from "./components/add-image-dialog-component";

function App() {

  const [canvasFns, setCanvasFns] = React.useState({});
  const [showAddTextDialog, setShowAddTextDialog] = React.useState(false);
  const [showAddImageDialog, setShowAddImageDialog] = React.useState(false);
  const [clickPosition, setClickPosition] = React.useState({});

  function onAddTextOpenDialogListener(clickPosition) {
    setShowAddTextDialog(true);
    setClickPosition(clickPosition);
  }
  function onAddImageOpenDialogListener(clickPosition) {
    setShowAddImageDialog(true);
    setClickPosition(clickPosition);
  }


  return (
    <>
      <Header></Header>
      <Canvas
        onAddImageOpenDialogListener={onAddImageOpenDialogListener}
        onAddTextOpenDialogListener={onAddTextOpenDialogListener}
        onCanvasReadyListener={setCanvasFns}
        show={showAddTextDialog === true || showAddImageDialog === true}></Canvas>
      <AddTextDialog
        canvasFns={canvasFns}
        show={showAddTextDialog}
        onDialogCloseListener={() => setShowAddTextDialog(false)}
        clickPosition={clickPosition}
      ></AddTextDialog>
      <AddImageDialog
        canvasFns={canvasFns}
        show={showAddImageDialog}
        onDialogCloseListener={() => setShowAddImageDialog(false)}
        clickPosition={clickPosition}
      ></AddImageDialog>
    </>
  );
}

export default App;
